language: node_js
node_js:
  - '10'

services:
  - docker

before_install:
  - npm i omg

script:
  - npx omg build
  - |
    output="$(npx omg run --raw message -a name="World" | jq -c .)"
    if [ "$output" != '{"message":"Hello World"}' ] ; then echo "$output"; exit 1; fi
